name: quote_keeper
description: A new Flutter project.
publish_to: "none"

version: 25.9.3+175

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  algoliasearch: ^1.2.0
  animated_search_bar: ^2.7.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.2
  dotted_border: ^3.1.0
  feedback: ^3.0.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  flutter_animate: ^4.1.1+1
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.1
  flutter_login: ^5.1.0
  flutter_riverpod: ^2.3.6
  flutter_settings_ui: ^3.0.1
  flutter_speed_dial: ^7.0.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  googleapis: ^14.0.0
  google_sign_in: ^6.3.0
  go_router: ^16.2.1
  http: ^1.1.0
  infinite_scroll_pagination: ^5.1.1
  image_cropper: ^9.1.0
  image_picker: ^1.0.1
  intl: ^0.20.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  lottie: ^3.1.0
  material_design_icons_flutter: ^7.0.7296
  modal_util: ^25.9.1
  package_info_plus: ^8.3.1
  path_provider: ^2.1.2
  share_plus: ^11.1.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  timeago: ^3.3.0
  toastification: ^3.0.3
  universal_platform: ^1.1.0
  uuid: ^4.3.3
  fluo: ^3.0.0
  logger: ^2.6.1

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^2.5.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_forground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic
