// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3fwTeLyIoErtbZjqj9WWlooi6Hhf5KO0',
    appId: '1:20452466446:web:e1144e71c13e4ee8da015f',
    messagingSenderId: '20452466446',
    projectId: 'book-quotes-4e31c',
    authDomain: 'book-quotes-4e31c.firebaseapp.com',
    storageBucket: 'book-quotes-4e31c.appspot.com',
    measurementId: 'G-J8EMK54QHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOnjF8oBaSo45XB4M91C-rK0Eb1kIyG8o',
    appId: '1:20452466446:android:8a70d01e95146764da015f',
    messagingSenderId: '20452466446',
    projectId: 'book-quotes-4e31c',
    storageBucket: 'book-quotes-4e31c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQfuOnZt5ac2z8FGThmjPc6K_JrwSXUU',
    appId: '1:20452466446:ios:527ba9a3c78066cada015f',
    messagingSenderId: '20452466446',
    projectId: 'book-quotes-4e31c',
    storageBucket: 'book-quotes-4e31c.appspot.com',
    androidClientId: '20452466446-8tsij3scvblev1u41njif9p86l9rccei.apps.googleusercontent.com',
    iosClientId: '20452466446-nabv83mu68a0l2svcjths8u05ald9rdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.book-quotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtQfuOnZt5ac2z8FGThmjPc6K_JrwSXUU',
    appId: '1:20452466446:ios:da9c3370368a8cc8da015f',
    messagingSenderId: '20452466446',
    projectId: 'book-quotes-4e31c',
    storageBucket: 'book-quotes-4e31c.appspot.com',
    androidClientId: '20452466446-8tsij3scvblev1u41njif9p86l9rccei.apps.googleusercontent.com',
    iosClientId: '20452466446-n0pt6gcdnq6vh0gagqruo0ed5a04f92n.apps.googleusercontent.com',
    iosBundleId: 'com.example.demos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv3EoM4Dbs99Ixti8_PmmcvpwqsogW6bo',
    appId: '1:20452466446:web:965cb4c13f46ae82da015f',
    messagingSenderId: '20452466446',
    projectId: 'book-quotes-4e31c',
    authDomain: 'book-quotes-4e31c.firebaseapp.com',
    storageBucket: 'book-quotes-4e31c.appspot.com',
    measurementId: 'G-ERF5EYYNF2',
  );
}
